<div class="container pt-5 mt-5">
    <h1 class="text-center">Disclaimer of Third-Party Site & Charges</h1>
    <p>At your request, you are being re-directed to a third party site. We are the Direct Sales/Re-seller/Retailer of all major Cable &amp; Satellite Service providers in US for TV, Internet &amp; Phone Services.</p>
    <p><br></p>
    <p>You are about to access a third party site, the accuracy or completeness of the information, materials, services or the reliability of any service, advice, opinion, statement or other information displayed or distributed through it, Smartick Cable Services does not warrant. You shall access this site solely for purposes of payment of your New Connection/Subscription/bills/dues/Channel Modification/Uninstallation/Relocation and you understand and acknowledge that availing of any services offered on the site or any on any opinion, advice, statement, memorandum, or information available on the site shall be at your sole risk &amp; there may be an additional charges for these services, charged by Smartick Cable Services Only as a 3rd Party Charges for the New Bookings &amp; Services.</p>
    <p><br></p>
    <p>Smartick Cable Services and its affiliates, subsidiaries, employees, officers, directors and agents, expressly disclaim any liability for any deficiency in the services offered by <a href="<?= base_url()?>">www.smartickcableservices.com</a> site you are about to access. Neither Xfinity/Spectrum/Comcast nor any of its affiliates nor their directors, officers and employees will be liable to or have any responsibility of any kind for any loss that you incur in the event of any deficiency in the services to whom the site belongs, failure or disruption of the site of Smartick Cable Services, or resulting from the act or Comission of any other party involved in making this site or the data contained therein available to you, or from any other cause relating to your access to, inability to access, or use of the site or these materials. Smartick Cable Services is reseller/retailer of New signups &amp; channel upgrade or helps in account related issues, it may be chargeable, depending on services &amp; package customer choose at the time of Signup.</p>
    <p><br></p>
    <p>I hereby confirm that I am a resident of USA and I have read the legal disclaimer</p>
</div>